name: Neon Developer Days Actions Demo
run-name: e2e Testing with Neon Actions 🚀
on: [pull_request]
jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Get PR number
        id: get_pull_number
        run: | 
          pull_number=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          echo "pull_number=${pull_number}" >> $GITHUB_OUTPUT
          echo $pull_number
      - name: Create Branch
        uses: neondatabase/create-branch-action@update-v2
        with:
          project_id: ${{ secrets.NEON_PROJECT_ID }}
          branch_name: branch_pull_${{steps.get_pull_number.outputs.pull_number}}
          api_key: ${{ secrets.NEON_API_KEY }}
          username: ${{ secrets.PGUSERNAME }}
          password: ${{ secrets.PGPASSWORD }}
        id: create-branch
      - run: echo db_url ${{ steps.create-branch.outputs.db_url}}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Prisma Migrate
        run: |
          touch .env
          echo DATABASE_URL=${DATABASE_URL} >> .env
          echo SHADOW_DATABASE_URL=${SHADOW_DATABASE_URL} >> .env
          npx prisma migrate dev
        env:
          DATABASE_URL: ${{ steps.create-branch.outputs.db_url}}/main
          SHADOW_DATABASE_URL: ${{ steps.create-branch.outputs.db_url}}/shadow
