name: Neon Developer Days Actions Demo
run-name: e2e Testing with Neon Actions 🚀
on: [pull_request]
jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: neondatabase/create-branch-action@update-v2
        with:
          project_id: ${{ secrets.NEON_PROJECT_ID }}
          branch_name: action_demo_branch
          api_key: ${{ secrets.NEON_API_KEY }}
          username: raouf
          password: password
        id: create-branch
      - run: echo db_url ${{ steps.create-branch.outputs.db_url}}
#       - uses: actions/checkout@v2
#       - run: npm install

