name: Neon Developer Days Actions Demo
run-name: e2e Testing with Neon Actions 🚀
on: [pull_request]
jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Create Neon Branch
        uses: neondatabase/create-branch-action@update-v2
        with:
          project_id: ${PROJECT_ID}
          branch_name: ${BRANCH_NAME}
          api_key: ${API_KEY}
          username: raouf
          password: password1234
        id: create-branch
        env:
          BRANCH_NAME: branch_from_action
          PROJECT_ID: secrets.NEON_PROJECT_ID
          API_KEY: ${{ secrets.NEON_API_KEY }}
      - run: echo db_url ${{ steps.create-branch.outputs.db_url}}
#       - uses: actions/checkout@v2
#       - run: npm install

