name: Merge
on:
  push:
    branches:
      - 'main'
jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Get PR number
        id: get_pull_number
        run: | 
          sha=$(jq --raw-output .push.before "$GITHUB_EVENT_PATH")
          echo "sha=${sha}" >> $GITHUB_OUTPUT
          echo $sha
